spring:
  application:
    name: notification
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
            required: flase
  #Rabbitmq Config
  rabbitmq:
    host: localhost
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5s
          multiplier: 2

#Rabbitmq Custom Config
rabbitmq:
  exchange:
    name: orders.v1.order-created
  queue:
    name: orders.v1.order-created.generate-notification