spring:
  application:
    name: processor
  datasource:
    url: jdbc:postgresql://localhost:5432/orderify_processor
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
