spring:
  application:
    name: orderify-api
#Rabbitmq Config
  rabbitmq:
    host: localhost
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}
    port: 5672

#SpringDoc OpenAPI
springdoc:
  swagger-ui:
    path: /api-docs.html
  api-docs:
    path: /api-docs
  packages-to-scan: br.com.orderify.controller

#Rabbitmq Custom Config
rabbitmq:
  exchange:
    name: orders.v1.order-created